<a href="https://colab.research.google.com/github/aecins/tutorials/blob/main/lie_groups_log_and_map_operators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sophuspy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.0/203.0 kB 4.5 MB/s eta 0:00:00


In [2]:
import numpy as np
import sophuspy as sp

# Create a random rotation represented in angleaxis.
rotation_angle = np.random.rand(1) * np.pi
rotation_axis = np.random.rand(3)
rotation_axis = rotation_axis / np.linalg.norm(rotation_axis)
rotation_angleaxis = rotation_axis * rotation_angle

In [3]:
# Convert it to a rotation matrix using the Rodrigues formula.
# This is equivalent to the Exp() operator on the SO(3) group that maps
# the R^3 vector elements to the SO(3) group elements.
def angleaxisToRotationMatrix(angleaxis):
    """Convert an angle-axis representation to rotation matrix using Rodrigues formula."""
    angle = np.linalg.norm(angleaxis)
    axis = angleaxis / angle

    kx = axis[0]
    ky = axis[1]
    kz = axis[2]

    K = np.array([[ 0, -kz,  ky],
                  [ kz,  0, -kx],
                  [-ky,  kx,  0]])

    return np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * np.matmul(K, K)

rotation_matrix = angleaxisToRotationMatrix(rotation_angleaxis)

In [4]:
# Create a Sophus SO3 object from angle axis representation.
rotation_so3_from_angleaxis = sp.SO3.exp(rotation_angleaxis)

# Check that it is repesented by the same matrix that we got from the Rodrigues formula.
print("Rotation matrix obtained using Rodrigues formula:")
print(rotation_matrix)
print("Rotation matrix obtained using Sophus:")
print(rotation_so3_from_angleaxis.matrix())

assert(np.all(np.absolute(rotation_matrix - rotation_so3_from_angleaxis.matrix()) < 1e-12))

Rotation matrix obtained using Rodrigues formula:
[[ 0.70903327 -0.06657699  0.70202516]
 [ 0.27427426 -0.89110946 -0.36152117]
 [ 0.64965026  0.44887797 -0.6135659 ]]
Rotation matrix obtained using Sophus:
[[ 0.70903327 -0.06657699  0.70202516]
 [ 0.27427426 -0.89110946 -0.36152117]
 [ 0.64965026  0.44887797 -0.6135659 ]]


In [5]:
# Create a Sophus SO3 object from a rotation matrix.
rotation_so3_from_matrix = sp.SO3(rotation_matrix)

# Check that converting the rotation matrix to angle axis using Sophus gives the expected result.
print("Original angleaxis:")
print(rotation_angleaxis)
print("Angleaxis obtained using Sophus:")
print(rotation_so3_from_matrix.log())
# This is equivalent to the Log operator on the SO(3) group that maps
# SO(3) group elements to R^3 vector elements.

assert(np.all(np.absolute(rotation_angleaxis - rotation_so3_from_matrix.log()) < 1e-12))

Original angleaxis:
[2.47115927 0.15970739 1.03936157]
Angleaxis obtained using Sophus:
[2.47115927 0.15970739 1.03936157]
